apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nuget-certs
  namespace: development
spec:
  secretName: nuget-certs
  duration: 8760h
  renewBefore: 720h
  commonName: lass
  dnsNames:
    - 'nuget.mirror.lass.net'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048   
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
