---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: development
spec:
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "rook-ceph-block"
---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo.config
  namespace: development
data:
  mongod.conf: |
    systemLog:
       destination: file
       path: "/var/log/mongodb/mongod.log"
       logAppend: true
    storage:
       dbPath: /data/db
       journal:
          enabled: true
    # Using a daemon(fork) in a container causes teh container to exit
    #processManagement:
    #   fork: true
    net:
       bindIp: 0.0.0.0
       port: 27017
    setParameter:
       enableLocalhostAuthBypass: true
    security:
        authorization: enabled
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo.user
  namespace: development
type: Opaque
data:
  username: cm9vdA==
  password: QWExMjM0NTY=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: development
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: mongo
          image: mongo:5.0.23
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 300Mi
          args:
            - --config 
            - /etc/mongo/mongod.conf
          ports:
            - containerPort: 27017
              name: tcp
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: mongo.user
                  key: username
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mongo.user
                  key: password
                  optional: false
          volumeMounts:
            - mountPath: /etc/mongo
              name: config
            - mountPath: /data
              name: pvc
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: mongo
        - name: config
          configMap:
            name: mongo.config

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: development
spec:
  ports:
    - port: 27017
      name: tcp 
      protocol: TCP
      targetPort: 27017
      nodePort: 30017
  selector:
    app: mongo
  sessionAffinity: None
  type: NodePort
#  type: ClusterIP
