---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: development
spec:
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "rook-ceph-block"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql.config
  namespace: development
data:
  my.cnf: |
    [client]
    default-character-set=utf8mb4
     
    [mysqld]
    port = 3306
    max_connections=1024
    character-set-server=utf8mb4
    default-storage-engine=INNODB
    skip-name-resolve
    
    [mysql]
    default-character-set=utf8mb4
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql.user
  namespace: development
type: Opaque
data:
  username: cm9vdA==
  password: QWExMjM0NTY=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: development
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: mysql
          image: mysql:8.0.30 
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 500Mi
          ports:
            - containerPort: 3306
              name: tcp
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mysql.user
                  key: password
                  optional: false
          volumeMounts:
            - mountPath: /etc/mysql/conf.d
              name: config
            - mountPath: /var/lib/mysql
              name: pvc
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: mysql
        - name: config
          configMap:
            name: mysql.config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: development
spec:
  ports:
    - port: 3306
      name: tcp 
      protocol: TCP
      targetPort: 3306
      nodePort: 30306
  selector:
    app: mysql
  sessionAffinity: None
  type: NodePort
#  type: ClusterIP
