apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hhd-pvc
  namespace: development
spec:
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 291Gi
  storageClassName: ""
