---
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pvc
#  namespace: development
#spec:
#  volumeMode: Filesystem
#  accessModes:
#   - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#  storageClassName: "rook-ceph-block"
