apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: ceph-admin
  namespace: gloo-system
spec:
  displayName: ceph-admin
  sslConfig:
    sniDomains:
    - ceph.rook.lass.net
  virtualHost:
    domains:
    - ceph.rook.lass.net
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: rook-ceph-rook-ceph-mgr-dashboard-8443
            namespace: gloo-system
