---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: hhd-pvc
#  namespace: development
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: ""
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tensorflow-serving
  name: tensorflow-serving
  namespace: development
spec:
  selector:
    matchLabels:
      app: tensorflow-serving
  template:
    metadata:
      labels:
        app: tensorflow-serving
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: tensorflow-serving
          image: tensorflow/serving:2.8.0-gpu
          imagePullPolicy: IfNotPresent
          args:
            - --model_config_file=/models/models.config
            - --model_config_file_poll_wait_seconds=60
          ports:
            - containerPort: 8500
              name: grpc
              protocol: TCP
            - containerPort: 8501
              name: http
              protocol: TCP
          resources:
          volumeMounts:
            - mountPath: /models
              name: pvc
              subPath: tensorflow/serving
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: hhd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow-serving
  namespace: development
spec:
  ports:
    - port: 8500
      name: grpc 
      protocol: TCP
      targetPort: 8500
    - port: 8501 
      name: http
      protocol: TCP
      targetPort: 8501
  selector:
    app: tensorflow-serving
  sessionAffinity: None
  type: ClusterIP
