#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: lass-pvc
#  namespace: development
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 100Gi
#  storageClassName: ""
#---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: tensorflow-job
  name: tensorflow-job
  namespace: development
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 1800
      backoffLimit: 3
      template:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          containers:
            - name: tensorflow-job
              image: tensorflow/tensorflow:2.8.1
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - 'cd /train_model/model && python ./model_preprocess.py ../data /save_model'
              volumeMounts:
                - mountPath: /train_model
                  name: pvc
                  subPath: tensorflow/train_model
                - mountPath: /save_model
                  name: pvc
                  subPath:  tensorflow/serving
                - mountPath: /usr/local/lib/python3.8/dist-packages
                  name: pvc
                  subPath: tensorflow/packages
          restartPolicy: Never
          volumes:
            - name: pvc
              persistentVolumeClaim:
                claimName: hhd-pvc
