apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hhd-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  storageClassName: ""
