apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
